# Generated by Django 4.1 on 2022-11-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crag', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='first_name',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last_name',
        ),
    ]
